language: python
python:
  - "3.8"
env:
  - VERILATOR_VERSION="4.102" # latest version@15/11/2020
  - VERILATOR_VERSION="4.100"
  - VERILATOR_VERSION="4.040"
  - VERILATOR_VERSION="4.038"
  - VERILATOR_VERSION="4.036"
  - VERILATOR_VERSION="4.034"
  - VERILATOR_VERSION="4.032"
  - VERILATOR_VERSION="4.030"
  - VERILATOR_VERSION="4.028" # oldest supported version
cache:
  directories:
    -  $TRAVIS_BUILD_DIR/verilator
before_install:
  - sudo apt-get update
  - sudo apt-get -y install git make autoconf g++
  - if [ ! -f verilator/INSTALLED ]; then git clone https://github.com/verilator/verilator.git; cd $TRAVIS_BUILD_DIR/verilator; git fetch origin; git checkout v$VERILATOR_VERSION; fi
  - cd $TRAVIS_BUILD_DIR/verilator && if [ "$(git pull)" != "Already up to date." ] || [ ! -f INSTALLED ]; then autoconf && ./configure && make -j2 && touch INSTALLED; fi && sudo make install && cd ..
install:
  - pip install -r requirements.txt
script:
  - python3 minimal_example.py