language: python
python:
  - "3.8"
env:
  - VERILATOR_VERSION="4.028"
cache:
  directories:
    -  $TRAVIS_BUILD_DIR/verilator
before_install:
  - sudo apt-get update
  - sudo apt-get -y install git make autoconf g++
  - if [ ! -f verilator/INSTALLED ]; then git clone https://github.com/verilator/verilator.git; git checkout v$VERILATOR_VERSION; fi
  - cd $TRAVIS_BUILD_DIR/verilator && if [ "$(git pull)" != "Already up to date." ] || [ ! -f INSTALLED ]; then autoconf && ./configure && make -j2 && touch INSTALLED; fi && sudo make install && cd ..
install:
  - pip install -r requirements.txt
script:
  - python3 minimal_example.py