name: DaCe Verilator Compatibility Check
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: python minimal_example.py
