name: DaCe Verilator Compatibility Check
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install apt packages
        run: sudo apt-get update && sudo apt-get -y install git make autoconf g++ flex bison libfl2 libfl-dev
      - name: compile verilator
        run: git clone https://github.com/verilator/verilator.git && cd verilator && autoconf && ./configure && make -j2 && sudo make install
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: python minimal_example.py
